name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install webdriver-manager
          pip install allure-pytest  # Install allure-pytest for reporting

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          google-chrome --version

      - name: Verify ChromeDriver Installation
        run: |
          python -c "from webdriver_manager.chrome import ChromeDriverManager; print(ChromeDriverManager().install())"

      - name: Install Allure
        run: |
          curl -o allure-2.24.1.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.1/allure-commandline-2.24.1.tgz
          sudo tar -zxvf allure-2.24.1.tgz -C /opt/
          sudo ln -s /opt/allure-2.24.1/bin/allure /usr/bin/allure
          allure --version

      - name: Run Tests with Allure
        run: |
          pytest --alluredir=allure-results -v --tb=short

      - name: Generate Allure Report
        run: |
          mkdir -p allure-results allure-report  # Ensure directories exist
          allure generate allure-results --clean -o allure-report

      - name: Install Netlify CLI
        run: |
          npm install -g netlify-cli
          netlify --version  # Verify Netlify CLI installation

      - name: Verify Netlify Site ID
        run: |
          echo "Deploying to Netlify site: $NETLIFY_SITE_ID"

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}  # Now using GitHub token
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          run: |
           netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir=allure-report --prod
