name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install webdriver-manager
          pip install allure-pytest  # Install Allure pytest plugin

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          google-chrome --version

      - name: Verify ChromeDriver Installation
        run: |
          python -c "from webdriver_manager.chrome import ChromeDriverManager; print(ChromeDriverManager().install())"

      - name: Install Allure
        run: |
          curl -o allure-2.24.1.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.1/allure-commandline-2.24.1.tgz
          sudo tar -zxvf allure-2.24.1.tgz -C /opt/
          sudo ln -s /opt/allure-2.24.1/bin/allure /usr/bin/allure
          allure --version

      - name: Run Tests with Allure
        run: |
          pytest --alluredir=allure-results -v --tb=short || true  # Ensures pipeline continues even if tests fail

      - name: Generate Allure Report
        if: always()  # Ensures report generation even if tests fail
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report as Artifact (Fixed)
        if: always()
        uses: actions/upload-artifact@v4  # ✅ Updated to v4
        with:
          name: Allure Report
          path: allure-report
          retention-days: 7  # Keep for 7 days

      - name: Deploy Allure Report to GitHub Pages
        if: success()  # Only deploy if pipeline is successful
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./allure-report
          force_orphan: true
